#!/usr/bin/env bash

DIR="/home/philosan/dwm/theme/rofi/"
STYLE="adaptive"
KILLER="$DIR/killer"
CONFIRM="$DIR/powermenu"

process=$(ps -eo pid,user,%cpu,%mem,comm --sort=-%cpu |
    tail -n +2 |
    rofi -dmenu \
        -i \
        -p "Kill process" \
		-theme ${KILLER} \
        -no-custom)

[ -z "$process" ] && exit 0

pid=$(awk '{print $1}' <<< "$process")
name=$(awk '{print $5}' <<< "$process")

confirm=$(printf "Cancel\nKill %s\nForce kill" "$name" |
    rofi -dmenu \
        -i \
        -theme ${CONFIRM} \
        -p "Confirm")

case "$confirm" in
    "Kill "*)
        kill "$pid"
        notify-send "Process killed" "$name ($pid)"
        ;;

    "Force kill "*)
        kill -9 "$pid"
        notify-send "Process force killed" "$name ($pid)"
        ;;
esac
