vim.opt.number = true                           -- set numbered lines
vim.opt.relativenumber = true                  -- set relative numbered lines
vim.opt.mouse = "a"                             -- allow the mouse to be used in neovim
vim.opt.smartcase = true                        -- smart case
--vim.opt.smartindent = true                      -- make indenting smarter again
vim.opt.hlsearch = false                         -- highlight all matches on previous search pattern
vim.opt.wrap = false                            -- display lines as one long line
vim.opt.splitbelow = true                       -- force all horizontal splits to go below current window
vim.opt.splitright = true                       -- force all vertical splits to go to the right of current window
vim.opt.clipboard=unnamedplus
