require "philo.options"
require "philo.keymaps"
require "philo.plugins"
require "philo.cmp"
require "philo.lsp"
require "philo.autopairs"
require "philo.nvim-tree"
require "philo.toggleterm"
require "philo.colorscheme"
require "philo.bar"
require "philo.tree_setter"
require "philo.buffer_line"
require "philo.dash"
require "philo.tel"
require "philo.color"
require "philo.git"
require "philo.comm"

