Section "InputClass"
       Identifier "tap-by-default libinput touchpad catchall"
       MatchIsTouchpad "on"
       MatchDriver "libinput"
       Option "Tapping" "on"
       Option "NaturalScrolling" "true"
       Option "DisableWhileTyping" "true"
       Option "ClickMethod" "clickfinger"
       Option "ScrollMethod" "twofinger"
       Option "PinchEnable" "true"
EndSection
